const otherQuotes = [
	{ type: 'text', content: `Don't mistake incompetence for conspiracy.` },
	{ type: 'text', content: `If motivation isn't working, try spite. Spite gets things done.` },
	{ type: 'text', content: `I know this is exactly what I asked for. I just want to change everything about it.` },
	{ type: 'text', content: `Why the long face? 🐴` },
	{ type: 'text', content: `Have you always had bangs?` },
	{ type: 'text', content: `The light at the end of the tunnel has been turned off due to budget cuts.` },
	{ type: 'text', content: `Dreams don’t work unless you do… and even then, maybe not.` },
	{ type: 'text', content: `It could be that your purpose in life is to serve as a warning to others.` },
	{ type: 'text', content: `Give up on your dreams, reduce expectations, and be pleasantly surprised.` },
	{ type: 'text', content: `Teamwork: because none of us is as dumb as all of us.` },
	{ type: 'text', content: `Hard work often pays off after time, but laziness always pays off now.` },
	{ type: 'text', content: `If at first you don’t succeed, skydiving is not for you.` },
	{ type: 'text', content: `Some people graduate with honors, I am just honored to graduate.` },
	{ type: 'text', content: `The best way to achieve your goals is to lower the bar.` },
	{ type: 'text', content: `You bring everyone so much joy… when you leave the room.` },
	{ type: 'text', content: `Mistakes were made… by someone else.` },
	{ type: 'text', content: `Always remember you’re unique… just like everyone else.` },
	{ type: 'text', content: `The road to success is always under construction.` },
	{ type: 'text', content: `Don’t be sad that your best wasn’t good enough. Be mad that you wasted your time.` },
	{ type: 'text', content: `Life is short. Smile while you still have teeth.` },
	{ type: 'text', content: `Success is just failure that hasn’t happened yet.` },
	{ type: 'text', content: `A balanced diet means a cookie in each hand.` },
	{ type: 'text', content: `If you aim for nothing, at least you’ll hit it.` },
	{ type: 'text', content: `Work hard today, so your boss can buy another vacation home.` },
	{ type: 'text', content: `You matter. Unless you multiply yourself by the speed of light squared… then you’re energy.` },
	{ type: 'text', content: `When life gives you lemons, squirt someone in the eye.` },
	{ type: 'text', content: `You can do anything you set your mind to… except maybe that.` },
	{ type: 'text', content: `Lower your expectations and you’ll never be disappointed.` },
	{ type: 'text', content: `If life gives you lemons, sell them and buy chocolate.` },
	{ type: 'text', content: `Don’t follow your dreams, follow my Instagram instead.` },
	{ type: 'text', content: `The best things in life are actually pretty expensive.` },
	{ type: 'text', content: `You have something special inside of you… mostly bones and organs.` },
	{ type: 'text', content: `The early bird gets the worm, but the second mouse gets the cheese.` },
	{ type: 'text', content: `Procrastinate now. Don’t put it off.` },
	{ type: 'text', content: `If you can’t beat them, arrange to have them beaten.` },
	{ type: 'text', content: `Nothing is impossible… for those who don’t have to do it.` },
	{ type: 'text', content: `You miss 100% of the naps you don’t take.` },
	{ type: 'text', content: `It’s not that I’m lazy. I just really enjoy doing nothing.` },
	{ type: 'text', content: `Your potential is limitless, but your effort isn’t.` },
	{ type: 'text', content: `You don’t have to be crazy to work here… we’ll train you.` },
	{ type: 'image', content: `https://i.imgur.com/uzxMNxP.jpeg` },
	{ type: 'image', content: `https://i.imgur.com/OyFFyov.jpeg` },
	{ type: 'image', content: `https://i.imgur.com/S2NmE5P.jpeg` },
	{ type: 'image', content: `https://i.imgur.com/2MqmMT8.jpeg` },
	{ type: 'image', content: `https://i.imgur.com/CzxtiYF_d.webp?maxwidth=520&shape=thumb&fidelity=high` },
	{ type: 'image', content: `https://i.imgur.com/5pkK0vH_d.webp?maxwidth=520&shape=thumb&fidelity=high` },
	{ type: 'image', content: `https://i.imgur.com/RdRY5Lo_d.webp?maxwidth=520&shape=thumb&fidelity=high` },
	{ type: 'image', content: `https://i.imgur.com/58iOify_d.webp?maxwidth=520&shape=thumb&fidelity=high` },
	{ type: 'image', content: `https://i.imgur.com/hQQTmzg_d.webp?maxwidth=520&shape=thumb&fidelity=high` },
	{ type: 'image', content: `https://i.imgur.com/ySo9dVQ.mp4` },
  ];
  
  export default otherQuotes;
  