const otherQuotes = [
	`Don't mistake incompetence for conspiracy.`,
	`If motivation isn't working, try spite. Spite gets things done.`,
	`I know this is exactly what I asked for. I just want to change everything about it.`,
	`Why the long face? 🐴`,
	`Have you always had bangs?`,
	`The light at the end of the tunnel has been turned off due to budget cuts.`,
	`Dreams don’t work unless you do… and even then, maybe not.`,
	`It could be that your purpose in life is to serve as a warning to others.`,
	`Give up on your dreams, reduce expectations, and be pleasantly surprised.`,
	`Teamwork: because none of us is as dumb as all of us.`,
	`Hard work often pays off after time, but laziness always pays off now.`,
	`If at first you don’t succeed, skydiving is not for you.`,
	`Some people graduate with honors, I am just honored to graduate.`,
	`The best way to achieve your goals is to lower the bar.`,
	`You bring everyone so much joy… when you leave the room.`,
	`Mistakes were made… by someone else.`,
	`Always remember you’re unique… just like everyone else.`,
	`The road to success is always under construction.`,
	`Don’t be sad that your best wasn’t good enough. Be mad that you wasted your time.`,
	`Life is short. Smile while you still have teeth.`,
	`Success is just failure that hasn’t happened yet.`,
	`A balanced diet means a cookie in each hand.`,
	`If you aim for nothing, at least you’ll hit it.`,
	`Work hard today, so your boss can buy another vacation home.`,
	`You matter. Unless you multiply yourself by the speed of light squared… then you’re energy.`,
	`When life gives you lemons, squirt someone in the eye.`,
	`You can do anything you set your mind to… except maybe that.`,
	`Lower your expectations and you’ll never be disappointed.`,
	`If life gives you lemons, sell them and buy chocolate.`,
	`Don’t follow your dreams, follow my Instagram instead.`,
	`The best things in life are actually pretty expensive.`,
	`You have something special inside of you… mostly bones and organs.`,
	`The early bird gets the worm, but the second mouse gets the cheese.`,
	`Procrastinate now. Don’t put it off.`,
	`If you can’t beat them, arrange to have them beaten.`,
	`Nothing is impossible… for those who don’t have to do it.`,
	`You miss 100% of the naps you don’t take.`,
	`It’s not that I’m lazy. I just really enjoy doing nothing.`,
	`Your potential is limitless, but your effort isn’t.`,
	`You don’t have to be crazy to work here… we’ll train you.`
  ];

  export default otherQuotes;