const quotes = [
	{ type: 'text', content: `Every day brings you one step closer.` },
	{ type: 'text', content: `The hardest battles lead to the greatest victories.` },
	{ type: 'text', content: `You've made it this far, keep going!` },
	{ type: 'text', content: `Tough times don't last, but tough people do.` },
	{ type: 'text', content: `Your future self will thank you for your persistence.` },
	{ type: 'text', content: `You are stronger than your annoyances.` },
	{ type: 'text', content: `Progress, no matter how small, is still progress.` },
	{ type: 'text', content: `Hold on. The storm always passes.` },
	{ type: 'text', content: `Every second survived is proof of your strength.` },
	{ type: 'text', content: `The best view comes after the hardest climb.` },
	{ type: 'text', content: `Keep moving forward, the goal is near.` },
	{ type: 'text', content: `Difficult roads often lead to beautiful destinations.` },
	{ type: 'text', content: `Your resilience is your superpower.` },
	{ type: 'text', content: `It's always darkest before the dawn.` },
	{ type: 'text', content: `You've conquered 100% of your hardest days.` },
	{ type: 'text', content: `Each moment is a chance to rewrite your story.` },
	{ type: 'text', content: `No pressure, no diamonds.` },
	{ type: 'text', content: `Believe in the strength that brought you here.` },
	{ type: 'text', content: `Your struggles are shaping something incredible.` },
	{ type: 'text', content: `Small steps add up to big changes.` },
	{ type: 'text', content: `You're not alone; keep pushing forward.` },
	{ type: 'text', content: `You've survived everything work life has thrown at you so far.` },
	{ type: 'text', content: `Your future self is cheering you on.` },
	{ type: 'text', content: `The only way out is through.` },
	{ type: 'text', content: `Better days are coming, one day at a time.` },
	{ type: 'text', content: `There should be a social media post about this.` },
	{ type: 'text', content: `Congratulations! You've made it this far without spontaneously combusting. Might as well keep going.` },
	{ type: 'text', content: `Look at you, still standing. What a shame for those who doubted you.` },
	{ type: 'text', content: `Success is just failure that didn't give up. So keep failing upward!` },
	{ type: 'text', content: `You've survived 100% of your worst days. Guess you're stuck being awesome.` },
	{ type: 'text', content: `Be patient. Rome wasn't built in a day… but I'm sure they at least started.` },
	{ type: 'text', content: `If at first you don't succeed, maybe lower your standards? Nah, keep trying.` },
	{ type: 'text', content: `You're not behind. You're just fashionably late to your own greatness.` },
	{ type: 'text', content: `You're like a WiFi signal. Stronger than you think but occasionally unstable.` },
	{ type: 'text', content: `The comeback is always stronger than the setback… unless you just sit there.` },
	{ type: 'text', content: `That thing you're avoiding? Yeah, it's still there. Handle it.` },
	{ type: 'text', content: `I believe in you, even if your to-do list doesn't.` },
	{ type: 'text', content: `Life knocked you down? Get up and hit it back. Harder.` },
	{ type: 'text', content: `Quitting now would make all that suffering pointless.` },
	{ type: 'text', content: `You're one step closer to success. Or at least one step further from failure.` },
	{ type: 'text', content: `Breathe. Not because it's calming, but because passing out won't help.` },
	{ type: 'text', content: `You're not overwhelmed, you're just on expert mode.` },
	{ type: 'text', content: `Your potential is like a WiFi signal: stop standing in the wrong spot.` },
	{ type: 'text', content: `People have done more with less. You got this.` },
	{ type: 'text', content: `You didn't come this far just to come this far. Keep moving!` },
	{ type: 'text', content: `That "impossible" thing? Someone dumber than you has probably done it.` },
	{ type: 'text', content: `Get up, show up, and fake confidence until it's real.` },
	{ type: 'text', content: `Somewhere out there, someone is crushing it with half your talent. Step up.` },
	{ type: 'text', content: `Nobody's got time for your excuses, not even you.` },
	{ type: 'text', content: `You're doing great… at finding creative ways to procrastinate. Now go do the thing.` },
	{ type: 'text', content: `The best revenge is massive success. And looking really, really smug about it.` },
	{ type: 'text', content: `Success is a marathon, not a sprint. Stop complaining and keep running.` },
	{ type: 'text', content: `You'll either win or have an amazing "I survived this" story.` },
	{ type: 'text', content: `Remember: the universe is probably too busy to conspire against you.` },
	{ type: 'text', content: `Your comfort zone is boring. Get out of it before you fossilize.` },
	{ type: 'text', content: `You are a limited edition; stop acting like an expired coupon.` },
	{ type: 'text', content: `The only "easy" day was yesterday… and you complained about that too.` },
	{ type: 'text', content: `When you fall into a bottomless pit, you die of starvation.` },
	{ type: 'text', content: `Shoot for the stars. If you fail, at least you'll burn up on re-entry.` },
	{ type: 'text', content: `You're closer than you were yesterday... unless you spent all day procrastinating.` },
	{ type: 'text', content: `Keep pushing forward! If it gets worse, at least it'll make a great story.` },
	{ type: 'text', content: `Your future self is already rolling their eyes at you. Impress them.` },
	{ type: 'text', content: `Hard work pays off. Eventually. Hopefully. Maybe.` },
	{ type: 'text', content: `Your comfort zone is cozy, but so is a grave. Get moving.` },
	{ type: 'text', content: `The only thing standing between you and success is... well, probably a lot of things, actually.` },
	{ type: 'text', content: `Believe in yourself! Statistically speaking, you're bound to get something right eventually.` },
	{ type: 'text', content: `Great things take time. But mediocre things can be done right now. So, you know, get started.` },
	{ type: 'image', content: `https://i.imgur.com/KXOcMR8.gif` },
	{ type: 'image', content: `https://i.imgur.com/2zwLciB.png` },
	{ type: 'image', content: `https://i.imgur.com/SYYiTba_d.webp?maxwidth=520&shape=thumb&fidelity=high` },
	{ type: 'image', content: `https://i.imgur.com/7xONH97.jpeg` },
	{ type: 'image', content: `https://i.imgur.com/gJD2max.jpeg` },
	{ type: 'image', content: `https://i.imgur.com/6YDANUd.jpeg` },
	{ type: 'image', content: `https://i.imgur.com/tommxfm_d.webp?maxwidth=520&shape=thumb&fidelity=high` },
	{ type: 'image', content: `https://i.imgur.com/4SeDVUX_d.webp?maxwidth=520&shape=thumb&fidelity=high` },
	{ type: 'image', content: `https://i.imgur.com/5lhWQT4.jpeg` },
  ];
  
  export default quotes;
  