const quotes = [
	`Every day brings you one step closer.`,
	`The hardest battles lead to the greatest victories.`,
	`You've made it this far, keep going!`,
	`Tough times don't last, but tough people do.`,
	`Your future self will thank you for your persistence.`,
	`You are stronger than your annoyances.`,
	`Progress, no matter how small, is still progress.`,
	`Hold on. The storm always passes.`,
	`Every second survived is proof of your strength.`,
	`The best view comes after the hardest climb.`,
	`Keep moving forward, the goal is near.`,
	`Difficult roads often lead to beautiful destinations.`,
	`Your resilience is your superpower.`,
	`It's always darkest before the dawn.`,
	`You've conquered 100% of your hardest days.`,
	`Each moment is a chance to rewrite your story.`,
	`No pressure, no diamonds.`,
	`Believe in the strength that brought you here.`,
	`Your struggles are shaping something incredible.`,
	`Small steps add up to big changes.`,
	`You're not alone; keep pushing forward.`,
	`You've survived everything worklife has thrown at you so far.`,
	`Your future self is cheering you on.`,
	`The only way out is through.`,
	`Better days are coming, one day at a time.`,
	`There should be a social media post about this.`,
	`Congratulations! You've made it this far without spontaneously combusting. Might as well keep going.`,
	`DAAAAAANNNN!!!!!!!`,
	`KATIEEEEE!!!!`,
	`Is that Shannon?! SHANNNONN!!!`,
	`Look at you, still standing. What a shame for those who doubted you.`,
	`Success is just failure that didn't give up. So keep failing upward!`,
	`You've survived 100% of your worst days. Guess you're stuck being awesome.`,
	`Be patient. Rome wasn't built in a day… but I'm sure they at least started.`,
	`If at first you don't succeed, maybe lower your standards? Nah, keep trying.`,
	`You're not behind. You're just fashionably late to your own greatness.`,
	`You're like a WiFi signal. Stronger than you think but occasionally unstable.`,
	`The comeback is always stronger than the setback… unless you just sit there.`,
	`That thing you're avoiding? Yeah, it's still there. Handle it.`,
	`I believe in you, even if your to-do list doesn't.`,
	`Life knocked you down? Get up and hit it back. Harder.`,
	`Quitting now would make all that suffering pointless.`,
	`You're one step closer to success. Or at least one step further from failure.`,
	`Breathe. Not because it's calming, but because passing out won't help.`,
	`You're not overwhelmed, you're just on expert mode.`,
	`Your potential is like a WiFi signal: stop standing in the wrong spot.`,
	`People have done more with less. You got this.`,
	`You didn't come this far just to come this far. Keep moving!`,
	`That "impossible" thing? Someone dumber than you has probably done it.`,
	`Get up, show up, and fake confidence until it's real.`,
	`Somewhere out there, someone is crushing it with half your talent. Step up.`,
	`Nobody's got time for your excuses, not even you.`,
	`You're doing great… at finding creative ways to procrastinate. Now go do the thing.`,
	`The best revenge is massive success. And looking really, really smug about it.`,
	`Success is a marathon, not a sprint. Stop complaining and keep running.`,
	`You'll either win or have an amazing "I survived this" story.`,
	`Remember: the universe is probably too busy to conspire against you.`,
	`Your comfort zone is boring. Get out of it before you fossilize.`,
	`You are a limited edition; stop acting like an expired coupon.`,
	`The only "easy" day was yesterday… and you complained about that too.`,
	`When you fall into a bottomless pit, you die of starvation.`,
	`Shoot for the stars. If you fail, at least you'll burn up on re-entry.`,
	`You're closer than you were yesterday... unless you spent all day procrastinating.`,
	`Keep pushing forward! If it gets worse, at least it'll make a great story.`,
	`You didn't come this far to only come this far... but taking a break sounds nice too.`,
	`Your future self is already rolling their eyes at you. Impress them.`,
	`Dream big! But also, maybe set an alarm so you actually wake up and do something.`,
	`Hard work pays off. Eventually. Hopefully. Maybe.`,
	`Your comfort zone is cozy, but so is a grave. Get moving.`,
	`The only thing standing between you and success is... well, probably a lot of things, actually.`,
	`Get up and grind! Or at least get up. Let's start there.`,
	`You're not failing, you're just collecting data for your comeback.`,
	`Believe in yourself! Statistically speaking, you're bound to get something right eventually.`,
	`You got this! And by 'this' I mean another round of problems to deal with.`,
	`Don't stop now! You're *this* close to a breakthrough… or a breakdown. Either way, exciting!`,
	`Every expert was once a beginner. So technically, you're right on track for greatness… eventually.`,
	`Somewhere out there, someone with half your talent is outworking you. But their boss probably trusts them... so there's that.`,
	`Success is just failing a little less each time. So, congrats on sucking slightly less today!`,
	`No one else is going to do it for you. Trust me, they've got their own problems.`,
	`Great things take time. But mediocre things can be done right now. So, you know, get started.`,
	`You'll never know your full potential until you try… or unless someone finally notices how awesome you are.`,
  ];

  export default quotes;